#pragma once

#ifndef GENERAL_DEFINES_H

#define GENERAL_DEFINES_H

#define	IMAGE_WORM_HEIGHT	60
#define	IMAGE_WORM_WIDTH	60
#define IMAGE_START_WORM_CORD_X	21
#define	IMAGE_START_WORM_CORD_Y	17
#define IMAGE_OFFSET_CORD_X	(IMAGE_WORM_WIDTH-IMAGE_START_WORM_CORD_X)
#define IMAGE_OFFSET_CORD_Y	(IMAGE_WORM_HEIGHT-IMAGE_START_WORM_CORD_Y)


#define OFFSET_DX	5
#define OFFSET_DY	5
#define RECTANGLE_BASE_WIDTH 45
#define RECTANGLE_BASE_HEIGHT 43



#endif // !GENERAL_DEFINES_H
